### ISSUE TITLE
azure --setup :  fails to update .env file (wrong path)

### ISSUE THREAD

**Issue by stevebus** [jonbgallant/azure-iot-edge-dev-tool#24]
- fresh run of the docker container toolset
- created project edgesolution1 from within the /iotedge folder
- ran iotedgedev azure --setup      (run from the /iotedge folder)
- after logging into CLI via browdere, creating a new iothub, and new edge device, the script asks if I want to update my .env file 
- answer 'y', and get this error:

Update the current .env with these connection strings? [y/N]: y
ERROR: Could not backup /iotedge/.env to /iotedge/.env.backup
ERROR: [Errno 2] No such file or directory: '/iotedge/.env'

looks like it is looking for it in the /iotedge  folder vs. the /iotedge/edgesolution1 folder

**Comment by jonbgallant** [comment]
Can you test with latest container? Can you share the exact docker run command you are using?

**Comment by stevebus** [comment]
re-tested with the latest image.  I nuked both the container and the image from my machine and started over.  Same result as above.  
![edgedev-error](https://user-images.githubusercontent.com/11857454/36905588-5b091404-1df9-11e8-971f-1b2c9183354a.png)

I copied and pasted the docker run command directly from the instructions:

docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v c:/temp/iotedge:/iotedge jongallant/iotedgedev

**Comment by jonbgallant** [comment]
Ah. You have to Cd into the solution folder before you run azure setup. Unfortunately there is no easy secure way to CD from within a python module. 

I’ll keep this open so I have a better error message for this. 

Pls try again from the solution folder.

**Comment by stevebus** [comment]
that worked...    as you said, better error message and maybe just add a note to the readme mentioning that you need to do it as well

**Comment by jonbgallant** [comment]
"cd message" now outputted to console after solution create.
