### ISSUE TITLE
Change dockerfile for debug

### ISSUE THREAD

**Issue by jonbgallant** [jonbgallant/azure-iot-edge-dev-tool#32]
in the file Dockerfile.amd64.debug you need to change the last line from:
 
ENTRYPOINT ["dotnet", "filtermodule.dll"]
 
to
 
CMD ["dotnet", "filtermodule.dll"]

**Comment by jonbgallant** [comment]
@tripdubroot I was able to get debug working with ENTRYPOINT.  Were you seeing an issue?

**Comment by tripdubroot** [comment]
@jonbgallant I'll give it another shot and get back to you

**Comment by jonbgallant** [comment]
Could not repro.
