### ISSUE TITLE
build for Pi fails on looking for incorrect Dockerfile

### ISSUE THREAD

**Issue by bospoort** [jonbgallant/azure-iot-edge-dev-tool#34]
When you specify arm32v7 in .env, the tool looks for Dockerfile.debug instead of Dockerfile.arm32v7

iotedgedev modules --build
[]
PROCESSING DOCKER FILE: ./Dockerfile.debug

then it bombs out:

docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: Dockerfile.debug")

**Comment by jonbgallant** [comment]
This file needs to be updated to point to arm32v7 instead of .debug
azure-iot-edge-dev-tool\iotedgedev\template\modules\filtermodule\module.json

**Comment by jonbgallant** [comment]
Resolved. https://github.com/jonbgallant/azure-iot-edge-dev-tool/blob/81e6c6ba9b32ac2b0824a60ead4987fd77554191/iotedgedev/template/modules/filtermodule/module.json
