### ISSUE TITLE
Need help setting up CI\CD

### ISSUE THREAD

**Issue by rahulrai-in** [jonbgallant/azure-iot-edge-dev-tool#37]
I created the following batch file which I invoke from VSTS Hosted Agent 2017.

python -m pip install azure-iot-edge-dev-tool
iotedgedev modules --build

Though the installation of iotedgedevtools happen fine. When the second statement executes, I get an error: 'iotedgedev' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jonbgallant** [comment]
Hi @rahulrai-in 

Here's what I do, (will doc this soon as well)

1. Linux Hosted Agent. Should work with others as well.

1. Store the .env file in Library -> Secure Files
![image](https://user-images.githubusercontent.com/2163001/37007626-16db81e4-2093-11e8-9dad-44e4d47bdaaf.png)

1. Use this extension to download the file into working directory
https://marketplace.visualstudio.com/items?itemName=carlowahlstedt.SecureFiles

![image](https://user-images.githubusercontent.com/2163001/37007681-5e8887a8-2093-11e8-9115-20216b2b47e4.png)

![image](https://user-images.githubusercontent.com/2163001/37007691-6405b994-2093-11e8-9e59-042702bc7992.png)

1. Add bash script task, select "Version 3.* preview"

![image](https://user-images.githubusercontent.com/2163001/37007700-7c717cc0-2093-11e8-9840-a4e7c5710d54.png)


LMK if you want to do a remote session and I can help you through it.

**Comment by rahulrai-in** [comment]
Thanks Jon,

I will follow the steps that you mentioned and let you know. We can connect over S4B, if you let me know your Microsoft alias. Or you can add me @ rahul.rai@readify.net. Thank you.

**Comment by rahulrai-in** [comment]
Jon,

I just tested the steps that you mentioned above. They work with Linux agent only and not with the Hosted Agent 2017, where I still get not found errors for PIP and IoTEdgeDev Tool. Anyways, we have both the agents available to us so that should be fine.

I need to know one more thing. How can I dynamically update the version number on each build, so that my image is generated with a fresh tag (can be a datetime). There is an issue in IoT Hub where the image is not pulled to edge device when the tags are not modified.

**Comment by jonbgallant** [comment]
Great. I’ll see about getting it to work on other hosts. 

For now, you can set the CONTAINER_TAG env var to something unique before you call build. 

set CONTAINER_TAG=“Something unique”
iotedgedev modules —build 

That will get injected into tag between version number and arch

Like :1.0.0-container_tag-amd64


I’ll add this as a back log item to Auto gen unique tag

**Comment by rahulrai-in** [comment]
Hi Jon,

An update:
I tried setting the variable to epoch timestamp through this statement just before the build:
`set CONTAINER_TAG = date +%s`
However, this value is not getting applied on the image.

**Comment by rahulrai-in** [comment]
Sorry, that was a mistake on my part. I am not very good with bash. I changed the statement to this and it works now. Thanks for your help.
```
CONTAINER_TAG=`date +%s`
export CONTAINER_TAG
```
