### ISSUE TITLE
Show how to map local drive to container on Linux

### ISSUE THREAD

**Issue by rahulrai-in** [jonbgallant/azure-iot-edge-dev-tool#45]
I want to set up the tool through container mechanism on Linux. The outlined steps talk about setting it up using WSL on windows. Can you elaborate the steps that should be followed for Linux OS?

**Comment by jonbgallant** [comment]
Are you asking how to run the tool in a container? If so https://github.com/jonbgallant/azure-iot-edge-dev-tool/blob/master/README.md#dev-machine-setup

**Comment by rahulrai-in** [comment]
Jon,

I followed the steps in the link. However, they seem to work on WIndows only. The mount paramter in the docker command doesn't work (maybe because I am not good with Linux). Can I bother you with a couple of questions over IM? Do you have a communication channel that I can use? Thanks.

**Comment by jonbgallant** [comment]
Ok. I get it. Linux is your host. What Linux variant are you running?

Let’s connect sometime tomorrow PST.

**Comment by rahulrai-in** [comment]
These are the distribution details:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Would you mind passing on your username on any channel? Thanks.

**Comment by jonbgallant** [comment]
You can use this command on Linux
```
docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /home/iotedge:/home/iotedge jongallant/iotedgedev
```

That will map your local /home/iotedge to the container's /home/iotedge
