### ISSUE TITLE
e2e - error when trying to create a resource group

### ISSUE THREAD

**Issue by buzzfrog** [jonbgallant/azure-iot-edge-dev-tool#59]
I use all defaults, including creating a new resource group with the default name.

=============================================
======== SETTING RESOURCE GROUP NAME ========
=============================================

Setting Resource Group Name to 'iotedgedev-rg'...

Checking if Resource Group 'iotedgedev-rg' exists...

Resource Group iotedgedev-rg does not exist.
Creating Resource Group 'iotedgedev-rg' at ''...

ERROR: Could not create the new Resource Group iotedgedev-rg at location:.

**Comment by buzzfrog** [comment]
I think that it has to do with the Location, that is not set when you use the defaults

**Comment by jonbgallant** [comment]
Thanks for reporting. Will fix. For now call with

iotedgedev azure --resource-group-location westus 

Change westus to whatever location you need.

**Comment by jonbgallant** [comment]
This is fixed in 0.73.0

Please execute the following to get this version
`pip install -U azure-iot-edge-dev-tool`
